### PR TITLE
RoughBench: BenchmarkReflector improvements.

### PR DESCRIPTION
**Pull request by ScottLouvau**
Make BenchmarkReflector public to allow separate use.
Allow passing instance to invoke methods on.

These changes make it easy to benchmark methods where you want to control the object construction or call other methods (to verify the results of the tested operation, for example) afterward.

### CODE REVIEW

**Review by michaelcfanning — APPROVED** [review]
:shipit:

**Comment by eddynaka** [comment]
@ScottLouvau , I was taking a look at this and looks like the package `System.Runtime.Intrinsics.X86` isn't available at myget. Tried to migrate to `net5.0` and so some difficulties:
1. had to change to net5.0 since the experimental package requires it (that was easy)
2. one static method is gone: `Sse.StaticCast`

Do you know if we can replace that?

**Comment by eddynaka** [comment]
> @ScottLouvau , I was taking a look at this and looks like the package `System.Runtime.Intrinsics.X86` isn't available at myget. Tried to migrate to `net5.0` and so some difficulties:
> 
> 1. had to change to net5.0 since the experimental package requires it (that was easy)
> 2. one static method is gone: `Sse.StaticCast`
> 
> Do you know if we can replace that?

I took a look and I saw that it got replaced for something like this:
vect.AsInt32() or vect.AsSbyte(), so I changed to those.

**Comment by eddynaka** [comment]
@ScottLouvau , fixed the build issue but i had to migrate to net5.0. Let me know if that is ok.
Otherwise, we have to figure out another way.

**Comment by ScottLouvau** [comment]
Thanks, @eddynaka, for taking a look and getting it merged! I'm a little confused about what happened. I thought I only changed RoughBench and the associated project. It looks like my merge from master via the GitHub UI brought in the other changes. 

The only thing I'm consuming from elsewhere right now is the RoughBench library, which was and is still .netstandard2.0, so the target change should be no problem for me.

**Comment by ScottLouvau** [comment]
(Also, I didn't see a notification for your comments because my old work e-mail was still set to received notifications. That should be fixed now, so I should respond faster next time.)

**Comment by eddynaka** [comment]
@ScottLouvau , no worries! :)

sorry for taking ur work, but now it's merged. let me know if u face more problems.
thanks again for the contribution 👍

**Pull request merged**
